#! /usr/bin/env python3

from text   import Scanner
from syntax import Parser
from sys    import argv
from utils  import Error


def tokenize(files):
    toks = []

    for fn in files:
        with open(fn, "r") as file_:
            toks += Scanner(file_).scan()
    
    return toks

def parse(toks):
    return Parser("test", toks).parse()


def main(args):
    print("\x1b[1;32m·: \x1b[37mDruid \x1b[mCompiler \x1b[1;32m:· \x1b[m")

    if len(args) < 2: Error("the compiler must take an option.")
    option = args[1]

    if option == 'compile':
        if len(args) < 3: Error("the 'compile' option must take at least one input file.")
        toks = tokenize(args[2:])
        ast = parse(toks)

        print(ast)
        

if __name__ == '__main__':
    main(argv)
